### ISSUE TITLE
daric normalize: missing chromosome

### ISSUE THREAD

**Issue by mzytnicki** [ykai16/DARIC#2]
First, let me thank you for solving the issue #1.

I now proceed to next step, which is `daric normalize`.

As you may have seen in my bw file, I focussed the analysis to autosomes.  Namely, I discarded `chrX` and `chrY`.

When I use `daric normalize`, I end up with the following error: 

    [...]
    File "[...]/DARIC/DARIC-v0.2.18/DARIC-v0.2.18_venv/lib/python3.9/site-packages/daric/lib/normalization.py", line 84, in normalize
      if start in pis[chrom].keys():
    KeyError: 'chrX'

Would it possible to correct this?
You could, for instance adding something like `if chrom in pis`, or simply remove the chromosome if it not present, just like you did line 50 in `normalization.py`, where you remove `chrY`?

I thank you again much for your help.

**Comment by ykai16** [comment]
Thanks for the comment. 

I managed to add a patch to get around of error. Please uninstall and reinstall DARIC using pip and try again. 

There should be no such error for "daric hmm". But if you have the similar error or any other errors, just let me know.

**Comment by mzytnicki** [comment]
This works like a charm, thanks!
